version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: task_container
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: task.io
      NGINX_PORT: 80
    volumes:
      - ./../.:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/sites-available/:/etc/nginx/sites-available
      - ./nginx/snippets/:/etc/nginx/snippets
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - internal
  php-fpm:
    image: php:7.4-fpm
    container_name: task_php
    build:
      context: php-fpm
    expose:
      - "9000"
    environment:
      NGINX_RUN_USER: "user"
    user: "user"
    volumes:
      - ./../.:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/24
